{% set name = "permission" %}
{% set version = "0.4.1" %}
{% set sha256 = "f2cd126123fb9f3f4f80a9640cf3aea688b06701525e02c25aa17221c0d871c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - permission

about:
  home: https://github.com/hustlzp/permission
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple and flexible permission control for Flask-style apps'

  description: |
    Simple and flexible permission control for Flask-style apps. It features
    simple (all you need to do is subclassing Rule and Permission class), and
    flexible (support rule inheritance and bitwise operations(& and |) to build
    your own rules) design.
  dev_url: https://github.com/hustlzp/permission

extra:
  recipe-maintainers:
    - frol
