travis:
  secure:
    BINSTAR_TOKEN: W5eI+3mdngX9+eWIX5xUGxlUvNz8K7/L4OgkP+a+s0hyv38aWbs+Yf8lXpymYbhxrUlb6AM5vgX3wzXnzX7W2/L3KKMymhfsIbr3KdtTLogcnpXyYB0A9NNLhDDT9C1ScFUKK7rxy0SOcWmU5a1R1dxapoF+BrHsFY6p+pLuqhXch+nihFTU8ajLZqB0goKD6S55QzFy0X4UBSmjohIYxCMrskRom1ZCuDjwjHo2Qe3vOnh1QJrcVylBrmy+vnvtiCqRX4jZ75JbQ2neBGp1FT+X/X4R5s79pRYq1cFjpsYv9/C9QI0u4PFWthdXOfqB2c0JwjSP8QY8Sz/hvRBM3emNfpGkPraS0XzO3nhEwrvTBkcxdyApKEcyD9dEyw4f7RAAxSEdfjbMHlZ3kKOYMjUl0ytcXqhQoCpzsSCEgMFAeFYX9a3y8M8uBPlMJxxXNAMdWlaT4EhwptvTd+fiBImbUrTbeGc22Yy0lyRpsCHCaYBmBZJoTJg9ev82GI0BqeMYcnanp+NpT5xmiuZFoYtHHsxQt5cxe8j17GN0NzZCPqLlH7y4Up2kQuCKwgPVbr5oc7zjNTfDL0uDp/YocjQoDRn+lb1gyc7WA2tvidVsDvWVKuCu1cPQjXzAWzgRrXvZGcsI22ycR5baA4mPFm9g7DEBCavtyIQzsbp45X8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
