travis:
  secure:
    BINSTAR_TOKEN: qLfLJ8OzjnTldPQ9dJEvmQzyY7XZ5IXPGWZzmE5t3jWfaiOJ2C2Y2JsSn7nPE6mzw9QLh87Imr+A+H/apruMZG3eyxkr6MeTYpd7dmaZYmHoJbuXUuhWFS97fF8Z+TOSWiDEvwXIL6RY0JAmRNkpkGt5L4KEHuFy6NSg+nrSP8OgEBeX3l2Bpff7n1gtch4CS2yFV0svs/OykHEvauLLs8GcJOTjpViZR/rD/d+QcLuKtaxaJQQnF4fIT2xb70XORZ6KH1xPfi1cTj42HgbuMozO0HqygJ+elgIdEV/3dqURJpo9yZBu4reMSOSp3Uim8XVHsBdiU1rz5lqESKkpuZmKukWEERermaCe8uJJkv1AJLG52D7WVQz52rCzzR4brp9i2SBGOc/61VSqH8FBysultBEFzZbuUxgcozIabxPopwRpuHo/S2k23rbKWXbs7TN+gdbaNA/DeWuZ5Kuj87ZMerWKNWLsQSxQz8EoTExnRquJf482t+EDyF490PKUrY5JKe8HWM997pZC612sNTL8T2WwF0SinXtcjtkC9qvLhIE/C7bDYG7AnmGm/T5pZIZAkJpS5UaK7chevNA2YKzNoEmIqkEz4zX8E8tL/Xn/VcPHpn8pqj+g3KcsNYusOuiI/hPHNlLH8l+cAROpgwNck3Rr0/nKBFIoLneDaTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
